name: Build rules

on:
  push:
    branches:
      - master
      - develop
    paths:
      - '.github/workflows/build.yml'
      - 'build/**/*'
      - 'rules.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'RyuaNerin/hide-online-marketplace' && github.event.head_commit.author.email != 'action@github.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'build/requirements.txt'

      - name: Install dependencies
        run: pip install -r build/requirements.txt

      - name: Build
        run: python build/build.py
          
      - name: Commit
        run: |
          git add filter.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Build rules" -a

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: master
          unprotect_reviews: true
